<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD4mneVz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD4mneVz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD4mneVz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD4mneVz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD4mneVz\App_KernelDevDebugContainer([
    'container.build_hash' => 'D4mneVz',
    'container.build_id' => 'f07a6f37',
    'container.build_time' => 1679501711,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD4mneVz');
