<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], [], []],
    'app_magasin_list' => [[], ['_controller' => 'App\\Controller\\MagasinController::index'], [], [['text', '/magasin/listProd']], [], [], []],
    'app_magasin_view' => [['id'], ['_controller' => 'App\\Controller\\MagasinController::viewLivre'], ['id' => '[1-9]\\d*'], [['variable', '/', '[1-9]\\d*', 'id', true], ['text', '/magasin/viewProd']], [], [], []],
    'app_magasin_add' => [[], ['_controller' => 'App\\Controller\\MagasinController::addLivre'], [], [['text', '/magasin/add']], [], [], []],
    'app_magasin_delete' => [['id'], ['_controller' => 'App\\Controller\\MagasinController::deleteAction'], ['id' => '[1-9]\\d*'], [['variable', '/', '[1-9]\\d*', 'id', true], ['text', '/magasin/delete']], [], [], []],
    'app_magasin_edit' => [['id'], ['_controller' => 'App\\Controller\\MagasinController::EditAction'], ['id' => '[1-9]\\d*'], [['variable', '/', '[1-9]\\d*', 'id', true], ['text', '/magasin/edit']], [], [], []],
    'app_profil_list' => [[], ['_controller' => 'App\\Controller\\ProfilController::index'], [], [['text', '/profil/list']], [], [], []],
    'app_profil_view' => [['id'], ['_controller' => 'App\\Controller\\ProfilController::viewProfil'], ['id' => '[1-9]\\d*'], [['variable', '/', '[1-9]\\d*', 'id', true], ['text', '/profil/view']], [], [], []],
    'app_profil_delete' => [['id'], ['_controller' => 'App\\Controller\\ProfilController::deleteAction'], ['id' => '[1-9]\\d*'], [['variable', '/', '[1-9]\\d*', 'id', true], ['text', '/profil/delete']], [], [], []],
    'app_profil_edit' => [['id'], ['_controller' => 'App\\Controller\\ProfilController::EditAction'], ['id' => '[1-9]\\d*'], [['variable', '/', '[1-9]\\d*', 'id', true], ['text', '/profil/edit']], [], [], []],
    'app_profil_add' => [[], ['_controller' => 'App\\Controller\\ProfilController::addProfil'], [], [['text', '/profil/add']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/security/login']], [], [], []],
    'app_add_user' => [[], ['_controller' => 'App\\Controller\\SecurityController::AddUserTest'], [], [['text', '/security/addusertest']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
